### ISSUE TITLE
Child node should not be able to link to parent node

### ISSUE THREAD

**Issue by mmonteiroc** [softflow24/data-river#117]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of data-river are you using?

Latest - Deployed version

### Describe your issue.

I should not be able to circularly link nodes "parent -> child -> parent"
<img width="857" alt="Screenshot 2024-10-09 at 21 19 19" src="https://github.com/user-attachments/assets/be8138e8-5c08-4b71-839c-f1da36db3dac">

### Paste Error from Terminal/Console

_No error in terminal_ :)

**Comment by itsWindows11** [comment]
@c0rtexR I'll work on this issue, feel free to assign.
