### ISSUE TITLE
[Bug] [Execution enginee] env variables are not resolved

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#122]
#### ⚠️ Before you continue
* Make sure you are using the [latest release](https://github.com/softflow24/data-river/releases).
* Join our [Discord](https://discord.gg/GjrVyZH9) to discuss or check if your issue is known.
* **Thoroughly search the [existing issues](https://github.com/softflow24/data-river/issues) before creating a new one**.

---

#### ⚠️ Search for existing issues first ⚠️
- [x] I have searched the existing issues, and there is no existing issue for my problem

---

### Describe the issue

**Issue**: The environment variables are not being resolved in the execution engine.

We have a `VariableResolver` class that is supposed to handle variable resolution within different scopes (`global`, `collection`, `environment`, `data`, `local`), and it seems like this part is working correctly, but we need to verify that.

```typescript
export class VariableResolver {
  private scopes: Record<Scope, Record<string, unknown>>;

  constructor() {
    this.scopes = {
      global: {},
      collection: {},
      environment: {},
      data: {},
      local: {},
    };
  }
}
```

However, when the execution engine resolves the inputs, it does not pass the resolved value to the receiver block. The issue seems to be in the executeWorkflow function, where resolvedInputs are created but not passed correctly during block execution.

```ts
async executeWorkflow(
  blockConfigs: IBlockConfig[],
): Promise<IExecutionResult> {
  this.logger.group("Executing Workflow");
  this.logger.time("Workflow Execution");

  let output: IExecutionResult = {
    result: [],
    errors: [],
  };
  for (const blockConfig of blockConfigs) {
    try {
      const inputs = this.getInputsForBlock(blockConfig);
      const resolvedInputs = this.resolveVariables(inputs);
      this.logger.debug(`Executing block: ${blockConfig.id}`, {
        blockConfig,
        resolvedInputs,
      });

      const updatedConfig = { ...blockConfig, inputs: resolvedInputs };
      const outputs = await this.executeBlockWithRetry(updatedConfig);

      this.logger.debug(`Block ${blockConfig.id} execution completed`, {
        outputs,
      });
      this.handleBlockOutputs(blockConfig, outputs);
      output.result.push({
        nodeType: blockConfig.type,
        nodeId: blockConfig.id,
        outputs,
        inputs: resolvedInputs,
      });
    } catch (error) {
      const blockError = this.handleBlockError(error as Error, blockConfig);
      this.environment.errors[blockConfig.id] = blockError.errors;
      output.errors.push({ blockId: blockConfig.id, error: error as Error });
      break;
    }
  }

  this.logger.timeEnd("Workflow Execution");
  this.logger.groupEnd();
  return output;
}
```

---

Operating System

[x] Linux

Which version of data-river are you using?

0.0.1

---

Describe your issue

The environment variables are being resolved by the VariableResolver, but during the execution, the resolved variables are not passed to the subsequent block. This prevents the workflow from functioning as expected because blocks are not receiving the expected inputs.

---

Paste Error from Terminal/Console (optional)

No specific errors were logged.

**Comment by geodask** [comment]
The environment variable resolution seems to be functioning correctly. Could the issue be limited to the logic block evaluation itself? If so, it seems that while the inputs are being passed correctly to the logic block, the issue might be in how those blocks are evaluated

**Comment by c0rtexR** [comment]
@geodask yeah you are correct my bad, resolving works, the logic block is evaluating condition wrong.

![image](https://github.com/user-attachments/assets/b98b1a20-b021-4eb8-a0dc-4cd34d00d287)

**Comment by itsWindows11** [comment]
Does the logic block execute properly if you set the input text to just `{{apiKey}}`? If so special handling should be needed for matches.

Regex could be used in this case if there isn't a more performant way.

**Comment by girl-loves-coding** [comment]
> Does the logic block execute properly if you set the input text to just `{{apiKey}}`? If so special handling should be needed for matches.
> 
> Regex could be used in this case if there isn't a more performant way.

It was a lot of talking for such a small fix XD

**Comment by itsWindows11** [comment]
> It was a lot of talking for such a small fix XD

bruh moment
