### ISSUE TITLE
Deletion of blocks

### ISSUE THREAD

**Issue by itsWindows11** [softflow24/data-river#128]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Being able to press the <kbd>Del</kbd> key, or right clicking on the block & selecting "Delete" should delete the block. Neither options currently exist.

The blocks that depend on the one that's deleted can be disconnected from the rest before it, but the workflow must not be able to run while it's disconnected.

Start & end blocks cannot be removed, and a toast pop-up should warn of that.

### Motivation 🔦

Deleting blocks is necessary in case the wrong block type is added by accident, or when a user wants to reset a block's settings.

**Comment by c0rtexR** [comment]
@itsWindows11 try backspace :)

**Comment by itsWindows11** [comment]
Backspace isn't a well known shortcut for deleting items, maybe characters but a block isn't a character 🤷‍♂️

**Comment by c0rtexR** [comment]
> Backspace isn't a well known shortcut for deleting items, maybe for characters but a block isn't a character 🤷‍♂️

I think it just comes like this by default from react-flow because of macs, most don't even have a delete button 😆 
With that being said, i do believe we can do better with handling this. I will mock something up for the context menu

**Comment by c0rtexR** [comment]
I'm closing the issue as it works, the UI just does not indicate to the user what are the shortcuts so can be confusing if you used to windows. Instead i have created an issue to address this by better UI on this issue https://github.com/softflow24/data-river/issues/136
