### ISSUE TITLE
[OKR] - Initial set up of monorepo

### ISSUE THREAD

**Issue by girl-loves-coding** [softflow24/data-river#42]
data-river/
├── packages/
│   ├── blocks/
│   │   ├── src/
│   │   ├── tests/
│   │   ├── package.json
│   │   └── tsconfig.json
│   ├── execution-engine/
│   │   ├── src/
│   │   │   ├── strategies/
│   │   │   ├── models/
│   │   ├── tests/
│   │   ├── package.json
│   │   └── tsconfig.json
│   ├── editor/
│   │   ├── src/
│   │   ├── public/
│   │   ├── tests/
│   │   ├── package.json
│   │   └── tsconfig.json
│   ├── server/
│   │   ├── src/
│   │   ├── tests/
│   │   ├── package.json
│   │   └── tsconfig.json
│   └── shared/
│       ├── interfaces/
│       │   ├── src/
│       │   ├── tests/
│       │   └── package.json
│       └── utils/
│           ├── src/
│           ├── tests/
│           └── package.json
├── node_modules/
├── lerna.json
├── package.json
├── tsconfig.base.json
└── README.md

### **Objective**:  
Set up a **monorepository** structure using **pnpm workspaces** to manage both the **Node.js backend** and **Vite frontend** efficiently, ensuring shared configuration across projects and optimized builds using **TurboRepo**.

---

### **Key Results**:

- [x] #49
  
- [x] #50

- [x] #51

- [x] #52

- [x] #53

---

### **Success Criteria**:
- The monorepository is fully functional, with shared configurations applied uniformly across both frontend and backend.
- The build process is optimized using **TurboRepo**, enabling parallel builds and faster development cycles.
- Both backend and frontend applications are fully tested, with CI/CD pipelines established to run tests in parallel.
- Achieve **100% compatibility** with **pnpm workspaces**, ensuring that all dependencies and scripts function as intended across projects.

---

### **Timeline**:  
Complete the monorepository setup and initial testing within **2 weeks**.

---

### **Additional Notes**:
- Set up CI/CD integration to automatically run tests and builds in the monorepository using **GitHub Actions** or similar CI tools.
- Regular code reviews and sync-ups to ensure all configurations remain consistent across the monorepo.

**Comment by iploooox** [comment]
We got most of this covered, missing only integration tests. Unit tests are already running in pipeline.

**Comment by girl-loves-coding** [comment]
@c0rtexR  can we add integration tests later and close this one?

**Comment by c0rtexR** [comment]
@girl-loves-coding let's do that.
