### ISSUE TITLE
Landing page - Jump in an explore button not working.

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#96]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of data-river are you using?

0.0.1

### Describe your issue.

On the landing page when you click on the first button "Jump In and Explore" it does not do anything.
What it should do is redirect you to docs.data-river.dev

**Comment by timomart** [comment]
@c0rtexR - PR for this issue: https://github.com/softflow24/data-river/pull/103

**Comment by iploooox** [comment]
@timomart thanks :) closing this.
