### ISSUE TITLE
Landing page - Quick Links section links are not working

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#97]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of data-river are you using?

0.0.1

### Describe your issue.

The links are not pointing to anything.

![image](https://github.com/user-attachments/assets/8b8e3fb3-a453-468f-a7f4-674e9d1d528f)

**Comment by mazilkhatib** [comment]
Added a commit about it but it in my pull request [https://github.com/softflow24/data-river/pull/111](url) 😅...
