### ISSUE TITLE
Landing page - Subscribe to newsletter button doesn't work.

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#98]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of data-river are you using?

0.0.1

### Describe your issue.

The button doesn't do anything after clicking.

![image](https://github.com/user-attachments/assets/510d04af-217f-41cf-8f27-2e8c757b1878)

**Comment by girl-loves-coding** [comment]
How to do: 
1. Go to Footer.tsx. There you can find the input field for email
2. Create a method that will grab the email from an input field and call the method to save the email in the database. 
3. Add validation to the input to make sure it is a valid email
4. Show the error notification if email is invalid.
5. Show a success notification when email is sorted successfully.  
6. Create a method to save email in the database.
7. Install a database locally, for example PostgreSQL pgAdmin, create a relevant schema for the table to store it in.

If you are in doubts from the technical perspective, do pair programming with chatGpt or better, install Cursor editor and chat with the Composer (much better AI ). We are also happy to assist you on Discord in development channel. To get data-river up and running locally watch this tutorial https://youtu.be/6A1-OiSFK7M?si=_b482Midm3Fx5MdY

**Comment by geodask** [comment]
Is someone working on it? If not, can start working on this?

**Comment by mazilkhatib** [comment]
[https://github.com/softflow24/data-river/pull/119](url)

**Comment by Saaaaaad3** [comment]
Hello. 
I would love to work on this issue and make a small contribution to the project. 
Please assign the issue to me.

**Comment by mazilkhatib** [comment]
@Saaaaaad3   I have already done this... you can check [My pull reques](https://github.com/softflow24/data-river/pull/119)

**Comment by girl-loves-coding** [comment]
@mazilkhatib can you please set the task in progress status and assign it to yourself 😉

**Comment by girl-loves-coding** [comment]
@mazilkhatib can you please set the task in progress status and assign it to yourself 😉

**Comment by girl-loves-coding** [comment]
@Saaaaaad3 it has already been picked up but haven't been set to the correct status. I will create a few issues today and post them on Discord in the development channel. Btw, I am very happy you want to contribute 🙂
